#' Convert an RTF file to HTML using Pandoc
#'
#' This function takes the path to an input RTF file and uses the Pandoc
#' command-line tool to convert it to HTML.
#'
#' @param file A string, the path to the input .rtf file.
#'
#' @return Character vector of HTML.
#'
#' @keywords internal
rtf_to_html <- function(file) {
  if (!file.exists(file)) {
    stop("Input RTF file does not exist: ", file)
  }

  if (Sys.which("pandoc") == "") {
    stop(
      "Pandoc command not found. ",
      "Please ensure Pandoc is installed and in your system's PATH."
    )
  }

  result <- system2(
    "pandoc",
    args = c("--from", "rtf", "--to", "html", shQuote(file)),
    stdout = TRUE,
    stderr = TRUE
  )

  status <- attr(result, "status", TRUE)
  if (length(status) > 0 && status > 0) {
    stop(c("Running Pandoc failed with following error", result))
  }

  return(paste0(result, collapse = "\n"))
}

#' Convert a string of HTML into a dataframe
#'
#' Convert the HTML generated by calling [rtf_to_html]() into a data frame.
#'
#' @param html A string, HTML generated by calling [rtf_to_html]().
#'
#' @return A data frame containing an R native version of the original RTF
#' table.
#'
#' @keywords internal
html_to_dataframe <- function(html) {
  html |>
    rvest::minimal_html() |>
    rvest::html_element("table") |>
    rvest::html_table()
}

#' Convert an RTF Table into an ARD data frame
#'
#' This function converts a table in RTF format into a data frame in R,
#' following the ARD standard. This is the top-level function of this package
#' which acts as a glue to the lower-level functions.
#'
#' @param file A string, the path to the input .rtf file.
#'
#' @return an R data frame following the ARD standard.
#'
#' @export
rtf_to_ard <- function(file) {
  file |>
    rtf_to_html() |>
    html_to_dataframe() |>
    strip_pagination() |>
    separate_indentation() |>
    pivot_group() |>
    separate_bign()
}
