# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "table_start", # <split_data>
  "shift_table_start", # <split_data>
  "table_id", # <split_data>
  "is_label", # <pivot_indentation>
  "label_id", # <pivot_indentation>
  "variable_label2", # <pivot_indentation>
  NULL
))
