# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "nbsp_count", # <strip_indentation>
  "counter", # <strip_indentation>
  "nbsp_group", # <strip_indentation>
  "indent_level", # <strip_indentation>
  "indent_level_rev", # <strip_indentation>
  "variable_label", # <strip_indentation>
  "value", # <strip_indentation>
  "variable_label0", # <strip_indentation>
  "variable_level", # <strip_indentation>
  "table_start", # <split_data>
  "shift_table_start", # <split_data>
  "table_id", # <split_data>
  "is_label", # <pivot_indentation>
  "label_id", # <pivot_indentation>
  "variable_label2", # <pivot_indentation>
  "group1_level", # <separate_bign>
  NULL
))
