#' Remove empty rows
#'
#' This function removes empty rows (where all cells are empty strings) inside a
#' data frame generated by calling [rtf_to_html()].
#'
#' @param data A data frame generated by calling [rtf_to_html()].
#'
#' @return A data frame with empty rows removed.
#'
#' @keywords internal
strip_empty_rows <- function(data) {
  filter(data, !if_all(everything(), ~ . == ""))
}

#' Remove the header
#'
#' This function removes the rows representing a header (e.g., titles and
#' subtitles) inside a data frame generated by calling [rtf_to_html()].
#'
#' @param data A data frame generated by calling [rtf_to_html()].
#'
#' @return A data frame with the header removed.
#'
#' @keywords internal
strip_header <- function(data) {
  # The second+ columns are populated with empty strings "" alongside the
  # header information which can be used to determine the row indices of the
  # header:
  header_last_row <- min(which(data[[2]] != "")) - 1

  # Some tables repeat across pages in the original RTF. This results in
  # data frames containing combined data frames with headers that repeat across
  # several points. Capture the original header:
  header_values <- data[[1]][1:header_last_row]

  # Remove all copies of the header:
  data[data[[1]] %!in% header_values, ]
}

#' Remove the footer
#'
#' This function removes the rows representing a footer inside a data frame
#' generated by calling [rtf_to_html()].
#'
#' @param data A data frame generated by calling [rtf_to_html()].
#'
#' @return A data frame with the footer removed.
#'
#' @keywords internal
strip_footer <- function(data) {
  # Placeholder
}

#' Remove pagination
#'
#' This function removes the rows representing pagination inside a data frame
#' generated by calling [rtf_to_html()]. These rows are signalled by repeated
#' column name headers. Only the first occurance should be kept.
#'
#' @param data A data frame generated by calling [rtf_to_html()].
#'
#' @return A data frame with the pagination removed.
#'
#' @keywords internal
strip_pagination <- function(data) {
  # Placeholder
}

#' Separate a single indented column into multiple columns
#'
#' This function separates a single indented column into multiple columns inside
#' a data frame generated by calling [rtf_to_html()]
#'
#' @param data A data frame generated by calling [rtf_to_html()].
#'
#' @return A data frame where indented columns have been separated.
#'
#' @keywords internal
separate_indentation <- function(data) {
  # Placeholder
}

#' Separate a merged columns into multiple columns
#'
#' This function separates columns containing merged values (e.g., where a count
#' and percentage are merged into a single string such as "34 (.56)") into
#' multiple columns inside a data frame generated by calling [rtf_to_html()].
#'
#' @param data A data frame generated by calling [rtf_to_html()].
#'
#' @return A data frame where merged columns have been separated.
#'
#' @keywords internal
separate_merges <- function(data) {
  # Placeholder
}

#' Separate a spanner
#'
#' This function separates spanning column labels out inside a data frame
#' generated by calling [rtf_to_html()]. A spanning column header represents a
#' unique grouping identifier for the columns it spans over.
#'
#' @param data A data frame generated by calling [rtf_to_html()].
#'
#' @return A data frame where merged columns have been separated.
#'
#' @keywords internal
separate_spanners <- function(data) {
  # Placeholder
}
